### ISSUE TITLE
change python interpreter?

### ISSUE THREAD

**Issue by DavidGoodwin** [bnchdan/MailLog2MySQL#1]
Does this actually require python3.9 ?

would 
```
#!/usr/bin/python3
```

be better?
Or /usr/bin/env python3 (if that works?)

https://github.com/bnchdan/MailLog2MySQL/blob/main/MailLog2MySQL

**Comment by bnchdan** [comment]
`Does this actually require python3.9 ?`

no. works with 
`#!/usr/bin/python3`
